/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}", "*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        // ── Stitch "Kinetic Obsidian" design tokens ──
        "surface-dim":              "#0e0e0e",
        "surface-container-high":   "#1f1f1f",
        "secondary":                "#8a95ff",
        "tertiary":                 "#ffa5d9",
        "tertiary-container":       "#ff8ed2",
        "primary-fixed-dim":        "#8387ff",
        "surface-tint":             "#a3a6ff",
        "secondary-container":      "#2f3aa3",
        "secondary-dim":            "#8a95ff",
        "surface-bright":           "#2c2c2c",
        "surface-container-low":    "#131313",
        "on-secondary-container":   "#c9cdff",
        "inverse-on-surface":       "#555555",
        "on-primary":               "#0f00a4",
        "inverse-surface":          "#f9f9f9",
        "primary":                  "#a3a6ff",
        "error-container":          "#a70138",
        "surface-container-highest":"#262626",
        "secondary-fixed-dim":      "#babfff",
        "outline-variant":          "#484848",
        "on-primary-container":     "#0a0081",
        "on-secondary":             "#000974",
        "secondary-fixed":          "#cbceff",
        "inverse-primary":          "#494bd7",
        "background":               "#000000",
        "tertiary-fixed":           "#ff8ed2",
        "primary-container":        "#9396ff",
        "surface-container":        "#191919",
        "primary-fixed":            "#9396ff",
        "surface-container-lowest": "#000000",
        "outline":                  "#757575",
        "primary-dim":              "#6063ee",
        "on-error":                 "#490013",
        "on-error-container":       "#ffb2b9",
        "tertiary-fixed-dim":       "#ef81c4",
        "on-background":            "#ffffff",
        "on-surface-variant":       "#ababab",
        "surface-variant":          "#262626",
        "error":                    "#ff6e84",
        "tertiary-dim":             "#ef81c4",
        "on-primary-fixed":         "#000000",
        "on-surface":               "#ffffff",
        "surface":                  "#0e0e0e",
        // Legacy tokens kept for existing component compatibility
        border:     "rgba(255,255,255,0.08)",
        input:      "#1f1f1f",
        ring:       "#a3a6ff",
        foreground: "#ffffff",
        muted: {
          DEFAULT:    "#1f1f1f",
          foreground: "#ababab",
        },
        accent: {
          DEFAULT:    "#1f1f1f",
          foreground: "#ffffff",
        },
      },
      fontFamily: {
        headline: ["Noto Serif", "Georgia", "serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
        mono:     ["Fira Code", "monospace"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm:  "0.5rem",
        md:  "0.75rem",
        lg:  "1.25rem",
        xl:  "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: 0 },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%":      { transform: "translateY(-10px)" },
        },
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%":      { transform: "translateY(-5px)" },
        },
        "kinetic-drift": {
          "0%":   { backgroundPosition: "0 0" },
          "100%": { backgroundPosition: "200px 200px" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        float:            "float 3s ease-in-out infinite",
        "bounce-slow":    "bounce-slow 4s ease-in-out infinite",
        "kinetic-drift":  "kinetic-drift 40s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};